#!/bin/bash 

SIZES=("8x8" "16x16" "24x24" "32x32" "48x48" "64x64" "128x128" "256x256" "512x512")
SCALES=('@2x')

find /usr/share/icons/Pop/ -type l -exec unlink {} \; || true

## Remove old HiDPI Folders
for SCALE in "${SCALES[@]}"
do
	for SIZE in "${SIZES[@]}"
	do
		# We don't care if the folders are already gone. This is only needed to 
		# ensure the HiDPI icons get installed
		rm -rf "/usr/share/icons/Pop/$SIZE$SCALE"
	done
done
