[Icon Theme]
Name=Pop-Mono-Dark
Comment=Pop's dark icon set for panels
Inherits=Pop,Adwaita,gnome,hicolor

# Directory list
Directories=22x22/animations,22x22/panel,24x24/animations,24x24/panel

# Animations

[22x22/animations]
Context=Animations
Size=22
Type=Fixed

[24x24/animations]
Context=Animations
Size=24
Type=Fixed

# Panel

[22x22/panel]
Context=Status
Size=22
Type=Fixed

[24x24/panel]
Context=Status
Size=24
Type=Fixed